# Generated by Django 5.1.2 on 2025-10-06 12:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="Permission key (e.g., 'reports.view')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Human-readable description of the permission')),
                ('category', models.CharField(blank=True, help_text='Permission category for organization', max_length=50)),
            ],
            options={
                'db_table': 'rbac_permissions',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('GRANT', 'Grant Permission'), ('REVOKE', 'Revoke Permission'), ('ASSIGN_ACCOUNT', 'Assign Account'), ('UNASSIGN_ACCOUNT', 'Unassign Account'), ('ASSIGN_PARENT', 'Assign Parent Network'), ('UNASSIGN_PARENT', 'Unassign Parent Network')], max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Reason for the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed the action', null=True)),
            ],
            options={
                'db_table': 'rbac_permission_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublisherAccountAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
            ],
            options={
                'db_table': 'rbac_publisher_account_access',
                'ordering': ['publisher__email', 'account__child_network_name'],
            },
        ),
        migrations.CreateModel(
            name='PublisherPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('manage_publishers', 'Manage Publishers'), ('settings', 'Settings'), ('managed_accounts', 'Managed Accounts'), ('reports', 'Reports')], max_length=50)),
            ],
            options={
                'db_table': 'accounts_publisher_permission',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin User'), ('PARENT', 'Parent Network User'), ('PUBLISHER', 'Publisher User')], help_text='User role', max_length=20)),
            ],
            options={
                'db_table': 'rbac_role_permissions',
                'ordering': ['role', 'permission__key'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(help_text='True to grant permission, False to deny')),
                ('reason', models.TextField(blank=True, help_text='Reason for this override')),
            ],
            options={
                'db_table': 'rbac_user_permission_overrides',
                'ordering': ['user__email', 'permission__key'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('admin', 'Admin User'), ('publisher', 'Publisher User'), ('parent', 'Parent Network User')], default='publisher', help_text='Admin: Full access. Publisher: Permission-based. Parent: Network-scoped access.', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('email_notifications', models.BooleanField(default=True)),
                ('slack_notifications', models.BooleanField(default=False)),
                ('slack_webhook_url', models.URLField(blank=True, help_text='Slack webhook for notifications')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('permissions_version', models.IntegerField(default=1, help_text='Version number for permission cache invalidation')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParentNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_parent_networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_parent_networks',
                'ordering': ['user__email'],
            },
        ),
    ]
