# Generated by Django 4.2.7 on 2025-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin User'), ('partner', 'Partner User')], default='partner', help_text='Admin: Full access. Partner: Permission-based access.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_webhook_url',
            field=models.URLField(blank=True, help_text='Slack webhook for notifications'),
        ),
    ]
