# Generated by Django 5.1.2 on 2025-10-19 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_publisher_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('crypto', 'Cryptocurrency (TRC20)'), ('wire', 'Wire Transfer')], help_text='Preferred payment method', max_length=20)),
                ('crypto_wallet_address', models.CharField(blank=True, help_text='TRC20 wallet address for crypto payments', max_length=255)),
                ('beneficiary_name', models.CharField(blank=True, help_text='Beneficiary name for wire transfer', max_length=255)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=255)),
                ('iban', models.CharField(blank=True, help_text='IBAN (International Bank Account Number)', max_length=50)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Bank country', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes or instructions')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payment Details',
                'db_table': 'accounts_payment_details',
            },
        ),
        migrations.AlterModelOptions(
            name='publisheraccountaccess',
            options={'ordering': ['publisher__email', 'child_network_code']},
        ),
        migrations.AddField(
            model_name='parentnetwork',
            name='parent_network_code',
            field=models.CharField(default='', help_text='Parent network code for managed inventory', max_length=20),
        ),
        migrations.AddField(
            model_name='parentnetwork',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_network_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='child_network_code',
            field=models.CharField(default='', help_text='Child network code for managed inventory', max_length=20),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='parent_network_code',
            field=models.CharField(default='', help_text='Parent network code for managed inventory', max_length=20),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_permission_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisheraccountaccess',
            name='child_network_code',
            field=models.CharField(default='', help_text='Child network code for managed inventory', max_length=20),
        ),
        migrations.AddField(
            model_name='publisheraccountaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_account_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisheraccountaccess',
            name='publisher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PUBLISHER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisherpermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='User who granted/revoked this override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin User'), ('publisher', 'Publisher User')], default='publisher', help_text='Admin: Full access. Publisher: Permission-based.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='publisheraccountaccess',
            unique_together={('publisher', 'child_network_code')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userpermissionoverride',
            unique_together={('user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['target_user', '-created_at'], name='rbac_permis_target__c0b9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['performed_by', '-created_at'], name='rbac_permis_perform_641a89_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['action', '-created_at'], name='rbac_permis_action_04cd1b_idx'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='user',
            field=models.OneToOneField(help_text='Publisher user', limit_choices_to={'role': 'publisher'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
