# Generated by Django 4.2.7 on 2025-07-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_login_ip_user_password_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('manage_mcm_invites', 'Manage MCM Invites'), ('verify_accounts', 'Verify Accounts'), ('access_reports', 'Access Reports'), ('manage_alerts', 'Manage Alerts'), ('access_tickets', 'Access Tickets')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_partner_permission',
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
