# Generated by Django 4.2.7 on 2025-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_partnerpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
