# Generated by Django 4.2.7 on 2025-07-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0003_assignedpartneraccount'),
        ('accounts', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpermission',
            name='parent_gam_network',
            field=models.ForeignKey(blank=True, help_text='Required for manage_mcm_invites', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gam_accounts.gamnetwork'),
        ),
    ]
