# Generated by Django 4.2.16 on 2026-03-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_site_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gam_type',
            field=models.CharField(choices=[('mcm', 'MCM (Child Network)'), ('o_and_o', 'Owned & Operated')], default='mcm', help_text='MCM: reports filtered by child network ID. O&O: reports filtered by site URL.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='network_id',
            field=models.CharField(blank=True, help_text="Publisher's GAM network ID (required for MCM, unused for O&O)", max_length=50),
        ),
    ]
