# Generated by Django 4.2.7 on 2025-10-04 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0017_alter_gamnetwork_api_version'),
        ('accounts', '0005_partnerpermission_parent_gam_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="Permission key (e.g., 'reports.view')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Human-readable description of the permission')),
                ('category', models.CharField(blank=True, help_text='Permission category for organization', max_length=50)),
            ],
            options={
                'db_table': 'rbac_permissions',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='partnerpermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions_version',
            field=models.IntegerField(default=1, help_text='Version number for permission cache invalidation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin User'), ('partner', 'Partner User'), ('parent', 'Parent Network User')], default='partner', help_text='Admin: Full access. Partner: Permission-based. Parent: Network-scoped access.', max_length=20),
        ),
        migrations.CreateModel(
            name='ParentNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_parent_networks', to=settings.AUTH_USER_MODEL)),
                ('parent_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_users', to='gam_accounts.gamnetwork')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_network_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_parent_networks',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(help_text='True to grant permission, False to deny')),
                ('reason', models.TextField(blank=True, help_text='Reason for this override')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted/revoked this override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_overrides', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='accounts.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_user_permission_overrides',
                'ordering': ['user__email', 'permission__key'],
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin User'), ('PARENT', 'Parent Network User'), ('PARTNER', 'Partner User')], help_text='User role', max_length=20)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
            ],
            options={
                'db_table': 'rbac_role_permissions',
                'ordering': ['role', 'permission__key'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('GRANT', 'Grant Permission'), ('REVOKE', 'Revoke Permission'), ('ASSIGN_PUBLISHER', 'Assign Publisher'), ('UNASSIGN_PUBLISHER', 'Unassign Publisher'), ('ASSIGN_PARENT', 'Assign Parent Network'), ('UNASSIGN_PARENT', 'Unassign Parent Network')], max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Reason for the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed the action', null=True)),
                ('parent_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_logs', to='gam_accounts.gamnetwork')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_permission_actions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.permission')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_logs', to='gam_accounts.mcminvitation')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_permission_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', '-created_at'], name='rbac_permis_target__c0b9b8_idx'), models.Index(fields=['performed_by', '-created_at'], name='rbac_permis_perform_641a89_idx'), models.Index(fields=['action', '-created_at'], name='rbac_permis_action_04cd1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerPublisherAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_publisher_access', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'PARTNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_publishers', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_partners', to='gam_accounts.mcminvitation')),
            ],
            options={
                'db_table': 'rbac_partner_publisher_access',
                'ordering': ['partner__email', 'publisher__child_network_name'],
                'unique_together': {('partner', 'publisher')},
            },
        ),
    ]
