# Generated by Django 4.2.30 on 2026-04-18 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_gam_type_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subdomain', models.CharField(db_index=True, help_text="Subdomain prefix (e.g. 'creator1' for creator1.publisher.com)", max_length=100, unique=True)),
                ('base_domain', models.CharField(help_text="Base domain (e.g. 'publisher.com')", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('dns_verified', models.BooleanField(default=False, help_text='Whether DNS for this subdomain has been verified')),
            ],
            options={
                'db_table': 'accounts_subdomain',
            },
        ),
        migrations.CreateModel(
            name='TrackingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_type', models.CharField(choices=[('utm', 'UTM Parameter'), ('subdomain', 'Subdomain')], help_text='UTM or Subdomain (one per sub-publisher)', max_length=20)),
                ('tracking_value', models.CharField(help_text="UTM source value (e.g. 'creator_john') or subdomain (e.g. 'john.publisher.com')", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'accounts_tracking_assignment',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('tracking', 'Tracking & Attribution'), ('earnings', 'Earnings & Payments'), ('reports', 'Reports & Analytics'), ('gam_setup', 'GAM Setup'), ('subdomains', 'Subdomain Configuration'), ('faq', 'FAQ')], default='getting_started', max_length=30)),
                ('content', models.TextField(help_text='Tutorial content in Markdown format')),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('is_published', models.BooleanField(default=True)),
                ('target_roles', models.JSONField(default=list, help_text='List of roles this tutorial is visible to (empty = all roles)')),
                ('video_url', models.URLField(blank=True, help_text='Optional video tutorial URL')),
            ],
            options={
                'db_table': 'accounts_tutorial',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Custom fee percentage assigned by partner-admin to this sub-publisher (0-100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_publisher',
            field=models.ForeignKey(blank=True, help_text='Partner-Admin who manages this sub-publisher', limit_choices_to={'role__in': ['partner_admin', 'admin']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='tracking_method',
            field=models.CharField(blank=True, choices=[('utm', 'UTM Parameter'), ('subdomain', 'Subdomain')], default='', help_text='Tracking method: UTM or Subdomain (one per publisher due to GAM limitations)', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentnetwork',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'partner_admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_network_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisheraccountaccess',
            name='publisher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'publisher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin User'), ('PARTNER_ADMIN', 'Partner Admin'), ('PUBLISHER', 'Publisher User'), ('SUB_PUBLISHER', 'Sub-Publisher')], help_text='User role', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='publisher',
            field=models.ForeignKey(help_text='Publisher who owns this site', limit_choices_to={'role__in': ['publisher', 'partner_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin User'), ('partner_admin', 'Partner Admin'), ('publisher', 'Publisher User'), ('sub_publisher', 'Sub-Publisher (Creator/Traffic Partner)')], default='publisher', help_text='Admin: Full access. Partner-Admin: Manages sub-publishers. Publisher: Permission-based. Sub-Publisher: Creator/traffic partner.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['parent_publisher', 'role'], name='accounts_us_parent__78d491_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='accounts_us_role_9fc6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorial',
            index=models.Index(fields=['category', 'is_published'], name='accounts_tu_categor_108a5f_idx'),
        ),
        migrations.AddField(
            model_name='trackingassignment',
            name='partner_admin',
            field=models.ForeignKey(help_text='Partner-admin who created this assignment', limit_choices_to={'role__in': ['partner_admin', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_tracking_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackingassignment',
            name='sub_publisher',
            field=models.OneToOneField(help_text='Sub-publisher this tracking is assigned to', limit_choices_to={'role': 'sub_publisher'}, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Sub-publisher assigned to this subdomain', limit_choices_to={'role': 'sub_publisher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subdomain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='partner_admin',
            field=models.ForeignKey(help_text='Partner-admin who owns this subdomain', limit_choices_to={'role__in': ['partner_admin', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trackingassignment',
            index=models.Index(fields=['tracking_type', 'tracking_value'], name='accounts_tr_trackin_0852e0_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingassignment',
            index=models.Index(fields=['partner_admin', 'is_active'], name='accounts_tr_partner_769f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackingassignment',
            constraint=models.CheckConstraint(check=models.Q(('tracking_type__in', ['utm', 'subdomain'])), name='valid_tracking_type'),
        ),
        migrations.AlterUniqueTogether(
            name='trackingassignment',
            unique_together={('partner_admin', 'tracking_value')},
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['partner_admin', 'is_active'], name='accounts_su_partner_947dde_idx'),
        ),
    ]
