# Generated by Django 5.1.2 on 2025-10-06 22:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_network_code', models.CharField(db_index=True, default='152344380', help_text='Parent GAM network code', max_length=20)),
                ('child_network_code', models.CharField(db_index=True, help_text='Child network code for direct filtering', max_length=20)),
                ('publisher_id', models.IntegerField(blank=True, db_index=True, help_text='Publisher assigned to this child network', null=True)),
                ('dimension_type', models.CharField(choices=[('overview', 'Overview'), ('site', 'App / Site'), ('trafficSource', 'Traffic Source'), ('deviceCategory', 'Device Category'), ('country', 'Country'), ('adunit', 'Ad Unit Name'), ('inventoryFormat', 'Inventory Format'), ('browser', 'Browser')], db_index=True, help_text='Type of dimension breakdown', max_length=32)),
                ('dimension_value', models.CharField(blank=True, help_text="Specific value for the dimension (e.g., 'United States' for country)", max_length=255, null=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date of the report data')),
                ('currency', models.CharField(default='USD', help_text='Currency for all monetary values (enforced as USD)', max_length=3)),
                ('impressions', models.BigIntegerField(default=0, help_text='Total impressions delivered')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue in USD', max_digits=20)),
                ('ecpm', models.DecimalField(decimal_places=2, default=0, help_text='Effective CPM (revenue per 1000 impressions)', max_digits=20)),
                ('clicks', models.BigIntegerField(default=0, help_text='Total clicks')),
                ('ctr', models.DecimalField(decimal_places=2, default=0, help_text='Click-through rate as percentage', max_digits=10)),
                ('eligible_ad_requests', models.BigIntegerField(default=0, help_text='Programmatic eligible ad requests')),
                ('viewable_impressions_rate', models.DecimalField(decimal_places=2, default=0, help_text='Viewable impressions rate as percentage', max_digits=8)),
                ('total_ad_requests', models.BigIntegerField(default=0, help_text='Total ad requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_metadata',
                'ordering': ['-date', 'dimension_type'],
                'indexes': [models.Index(fields=['date'], name='master_meta_date_977a40_idx'), models.Index(fields=['dimension_type', 'dimension_value'], name='master_meta_dimensi_367222_idx'), models.Index(fields=['parent_network_code'], name='master_meta_parent__e24fb1_idx'), models.Index(fields=['child_network_code'], name='master_meta_child_n_9516fb_idx'), models.Index(fields=['publisher_id'], name='master_meta_publish_53e9d4_idx'), models.Index(fields=['date', 'dimension_type', 'publisher_id'], name='master_meta_date_6909e2_idx'), models.Index(fields=['parent_network_code', 'date'], name='master_meta_parent__12a82f_idx'), models.Index(fields=['child_network_code', 'date'], name='master_meta_child_n_227b8d_idx')],
                'unique_together': {('child_network_code', 'date', 'dimension_type', 'dimension_value')},
            },
        ),
        migrations.CreateModel(
            name='ReportSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('total_networks_processed', models.IntegerField(default=0)),
                ('successful_networks', models.IntegerField(default=0)),
                ('failed_networks', models.IntegerField(default=0)),
                ('total_records_created', models.IntegerField(default=0)),
                ('total_records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('network_errors', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered manual sync', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
