# Generated by Django 4.2.7 on 2025-07-29 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gam_accounts', '0009_mcminvitation_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dimension_type', models.CharField(choices=[('overview', 'Overview'), ('appSite', 'App / Site'), ('trafficSource', 'Traffic Source'), ('deviceCategory', 'Device Category'), ('country', 'Country'), ('carrier', 'Carrier / ISP'), ('browser', 'Browser')], max_length=32)),
                ('dimension_value', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('impressions', models.BigIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('ecpm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('clicks', models.BigIntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('eligible_ad_requests', models.BigIntegerField(default=0)),
                ('viewable_impressions_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('total_ad_requests', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.mcminvitation')),
                ('parent_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.gamnetwork')),
            ],
            options={
                'db_table': 'master_meta_data',
                'indexes': [models.Index(fields=['date'], name='master_meta_date_65d447_idx'), models.Index(fields=['dimension_type'], name='master_meta_dimensi_68ebdc_idx'), models.Index(fields=['dimension_type', 'dimension_value'], name='master_meta_dimensi_c7f92f_idx'), models.Index(fields=['parent_network'], name='master_meta_parent__2d8b57_idx'), models.Index(fields=['invitation'], name='master_meta_invitat_92b549_idx'), models.Index(fields=['partner_id'], name='master_meta_partner_3a2297_idx'), models.Index(fields=['date', 'dimension_type', 'partner_id'], name='master_meta_date_85f966_idx')],
                'unique_together': {('invitation', 'date', 'dimension_type', 'dimension_value')},
            },
        ),
    ]
