# Generated by Django 5.1.2 on 2025-10-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermetadata',
            name='parent_network_code',
            field=models.CharField(default='152344380', max_length=50, help_text='Parent network code for managed inventory'),
        ),
    ]
