# Generated by Django 4.2.7 on 2025-07-29 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_dimensi_68ebdc_idx',
        ),
        migrations.AddField(
            model_name='mastermetadata',
            name='child_network_code',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='dimension_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('appSite', 'App / Site'), ('trafficSource', 'Traffic Source'), ('deviceCategory', 'Device Category'), ('country', 'Country'), ('carrier', 'Carrier / ISP'), ('browser', 'Browser')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='mastermetadata',
            index=models.Index(fields=['child_network_code'], name='master_meta_child_n_b01a9a_idx'),
        ),
    ]
