# Generated by Django 4.2.7 on 2025-08-04 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0010_alter_usernetworkpermission_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_remove_mastermetadata_master_meta_dimensi_68ebdc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('total_networks_processed', models.IntegerField(default=0)),
                ('successful_networks', models.IntegerField(default=0)),
                ('failed_networks', models.IntegerField(default=0)),
                ('total_records_created', models.IntegerField(default=0)),
                ('total_records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('network_errors', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'report_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='mastermetadata',
            options={'ordering': ['-date', 'dimension_type']},
        ),
        migrations.AddField(
            model_name='mastermetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='child_network_code',
            field=models.CharField(db_index=True, help_text='Child network code for direct filtering', max_length=20),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='clicks',
            field=models.BigIntegerField(default=0, help_text='Total clicks'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='ctr',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Click-through rate as percentage', max_digits=6),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date of the report data'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='dimension_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('appSite', 'App / Site'), ('trafficSource', 'Traffic Source'), ('deviceCategory', 'Device Category'), ('country', 'Country'), ('carrier', 'Carrier / ISP'), ('browser', 'Browser')], db_index=True, help_text='Type of dimension breakdown', max_length=32),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='dimension_value',
            field=models.CharField(blank=True, help_text="Specific value for the dimension (e.g., 'United States' for country)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='ecpm',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Effective CPM (revenue per 1000 impressions)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='eligible_ad_requests',
            field=models.BigIntegerField(default=0, help_text='Programmatic eligible ad requests'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='impressions',
            field=models.BigIntegerField(default=0, help_text='Total impressions delivered'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='invitation',
            field=models.ForeignKey(help_text='MCM invitation linking parent to child', on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.mcminvitation'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='parent_network',
            field=models.ForeignKey(help_text='Parent GAM network that fetched this data', on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.gamnetwork'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='partner_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Partner assigned to this child network', null=True),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='revenue',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Total revenue in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='total_ad_requests',
            field=models.BigIntegerField(default=0, help_text='Total ad requests'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='viewable_impressions_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Viewable impressions rate as percentage', max_digits=6),
        ),
        migrations.AddIndex(
            model_name='mastermetadata',
            index=models.Index(fields=['parent_network', 'date'], name='master_meta_parent__485d94_idx'),
        ),
        migrations.AddIndex(
            model_name='mastermetadata',
            index=models.Index(fields=['child_network_code', 'date'], name='master_meta_child_n_09f4cd_idx'),
        ),
        migrations.AddField(
            model_name='reportsynclog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered manual sync', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
