# Generated by Django 4.2.7 on 2025-08-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportsynclog_alter_mastermetadata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermetadata',
            name='unknown_clicks',
            field=models.BigIntegerField(default=0, help_text='Ad Exchange unknown clicks'),
        ),
        migrations.AddField(
            model_name='mastermetadata',
            name='unknown_impressions',
            field=models.BigIntegerField(default=0, help_text='Ad Exchange unknown impressions'),
        ),
        migrations.AddField(
            model_name='mastermetadata',
            name='unknown_revenue',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Ad Exchange unknown revenue in USD', max_digits=20),
        ),
        migrations.AddIndex(
            model_name='mastermetadata',
            index=models.Index(fields=['date', 'unknown_revenue'], name='master_meta_date_5b307e_idx'),
        ),
        migrations.AddIndex(
            model_name='mastermetadata',
            index=models.Index(fields=['child_network_code', 'unknown_revenue'], name='master_meta_child_n_ce82f8_idx'),
        ),
    ]
