# Generated by Django 4.2.30 on 2026-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_unified_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gammapping',
            new_name='tracking_ga_gam_ad__e3ce5e_idx',
            old_name='tracking_gm_aupath_idx',
        ),
        migrations.RenameIndex(
            model_name='gammapping',
            new_name='tracking_ga_gam_ad__4c8984_idx',
            old_name='tracking_gm_auid_idx',
        ),
        migrations.RenameIndex(
            model_name='gammapping',
            new_name='tracking_ga_gam_lin_cbd758_idx',
            old_name='tracking_gm_li_idx',
        ),
        migrations.RenameIndex(
            model_name='gammapping',
            new_name='tracking_ga_gam_net_b0a631_idx',
            old_name='tracking_gm_net_au_idx',
        ),
        migrations.RenameIndex(
            model_name='gammapping',
            new_name='tracking_ga_source__fe58a5_idx',
            old_name='tracking_gm_src_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_propert_aff44d_idx',
            old_name='mm_propid_date_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_placeme_7168a7_idx',
            old_name='mm_plcid_date_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_source__149c2c_idx',
            old_name='mm_srctype_date_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_publish_db3f4c_idx',
            old_name='mm_pub_prop_date_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyearning',
            new_name='report_mont_publish_c23249_idx',
            old_name='report_mont_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyearning',
            new_name='report_mont_status_b39bac_idx',
            old_name='report_mont_status_idx',
        ),
        migrations.RenameIndex(
            model_name='placement',
            new_name='tracking_pl_propert_0f0e8d_idx',
            old_name='tracking_pl_prop_st_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='tracking_pr_publish_33b490_idx',
            old_name='tracking_pr_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='tracking_pr_domain_0aa1b5_idx',
            old_name='tracking_pr_domain_idx',
        ),
        migrations.AlterField(
            model_name='gammapping',
            name='gam_ad_unit_path',
            field=models.CharField(blank=True, db_index=True, help_text='Full ad unit path, e.g. /23341212234/hnt/pub_42/prop_42_example_com/article_top_300x250', max_length=500),
        ),
        migrations.AlterField(
            model_name='gammapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='attribution_method',
            field=models.CharField(blank=True, choices=[('key_value', 'Key-Value Match'), ('ad_unit_path', 'Ad Unit Path Parse'), ('gam_mapping', 'GAM Mapping Table'), ('domain_match', 'Domain Match'), ('legacy', 'Legacy Fallback'), ('unattributed', 'Unattributed')], help_text='How this record was attributed to publisher/property/placement', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='child_network_code',
            field=models.CharField(db_index=True, help_text='Child network code or O&O domain for direct filtering', max_length=100),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='source_type',
            field=models.CharField(blank=True, choices=[('mcm_direct', 'MCM Direct'), ('gam360_passback', 'GAM 360 Passback'), ('prebid', 'Prebid'), ('open_bidding', 'Open Bidding'), ('adx_direct', 'AdX Direct'), ('house', 'House'), ('direct_campaign', 'Direct Campaign'), ('unknown', 'Unknown')], db_index=True, help_text='Demand source classification', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='ad_size',
            field=models.CharField(blank=True, help_text='Ad size, e.g. 300x250, 728x90, responsive', max_length=50),
        ),
        migrations.AlterField(
            model_name='placement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_id',
            field=models.CharField(db_index=True, help_text='Internal placement ID, e.g. plc_42_example_com_article_top_300x250', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_name',
            field=models.CharField(help_text='Human-readable name, e.g. Article Top 300x250', max_length=150),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcetyperule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcetyperule',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower = higher priority'),
        ),
    ]
