# Generated by Django 4.2.7 on 2026-04-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_extend_child_network_code_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_propert_aff44d_idx',
        ),
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_placeme_7168a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_source__149c2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_publish_db3f4c_idx',
        ),
        migrations.RemoveField(
            model_name='mastermetadata',
            name='attribution_method',
        ),
        migrations.RemoveField(
            model_name='mastermetadata',
            name='placement_id_tracking',
        ),
        migrations.RemoveField(
            model_name='mastermetadata',
            name='property_id_tracking',
        ),
        migrations.RemoveField(
            model_name='mastermetadata',
            name='source_type',
        ),
    ]
