# Generated by Django 4.2.7 on 2025-08-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportsynclog_alter_mastermetadata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermetadata',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency for all monetary values (enforced as USD)', max_length=3),
        ),
    ]
