# Generated by Django 4.2.16 on 2025-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_mastermetadata_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermetadata',
            name='dimension_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('site', 'App / Site'), ('trafficSource', 'Traffic Source'), ('deviceCategory', 'Device Category'), ('country', 'Country'), ('carrier', 'Carrier / ISP'), ('browser', 'Browser')], db_index=True, help_text='Type of dimension breakdown', max_length=32),
        ),
    ]
