# Generated by Django 4.2.16 on 2025-09-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_mastermetadata_dimension_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermetadata',
            name='unknown_revenue',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Revenue from desktop devices marked as unknown', max_digits=20),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='unknown_clicks',
            field=models.BigIntegerField(default=0, help_text='Ad Exchange unknown clicks (deprecated)'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='unknown_impressions',
            field=models.BigIntegerField(default=0, help_text='Ad Exchange unknown impressions (deprecated)'),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='unknown_revenue',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Ad Exchange unknown revenue in USD (deprecated)', max_digits=20),
        ),
    ]
