# Generated by Django 4.2.16 on 2025-09-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_mastermetadata_unknown_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermetadata',
            name='ctr',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Click-through rate as percentage', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='ecpm',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Effective CPM (revenue per 1000 impressions)', max_digits=20),
        ),
    ]
