# Generated by Django 4.2.16 on 2025-09-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_mastermetadata_ctr_alter_mastermetadata_ecpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermetadata',
            name='viewable_impressions_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Viewable impressions rate as percentage', max_digits=8),
        ),
    ]
