# Generated by Django 4.2.16 on 2025-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_mastermetadata_viewable_impressions_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermetadata',
            name='ctr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Click-through rate as percentage', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='ecpm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Effective CPM (revenue per 1000 impressions)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total revenue in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='unknown_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue from desktop devices marked as unknown', max_digits=20),
        ),
        migrations.AlterField(
            model_name='mastermetadata',
            name='viewable_impressions_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Viewable impressions rate as percentage', max_digits=8),
        ),
    ]
