# Generated by Django 4.2.16 on 2025-09-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_mastermetadata_ctr_alter_mastermetadata_ecpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermetadata',
            name='unknown_clicks',
            field=models.BigIntegerField(default=0, help_text='Clicks from desktop devices marked as unknown'),
        ),
        migrations.AddField(
            model_name='mastermetadata',
            name='unknown_ctr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CTR from desktop devices marked as unknown', max_digits=10),
        ),
        migrations.AddField(
            model_name='mastermetadata',
            name='unknown_ecpm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='eCPM from desktop devices marked as unknown', max_digits=20),
        ),
        migrations.AddField(
            model_name='mastermetadata',
            name='unknown_impressions',
            field=models.BigIntegerField(default=0, help_text='Impressions from desktop devices marked as unknown'),
        ),
    ]
