# Generated by Django 4.2.16 on 2025-09-09 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0011_alter_mcminvitation_user_status'),
        ('reports', '0011_mastermetadata_unknown_clicks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_network_code', models.CharField(db_index=True, help_text='Child network code for direct filtering', max_length=20)),
                ('partner_id', models.IntegerField(blank=True, db_index=True, help_text='Partner assigned to this child network', null=True)),
                ('dimension_type', models.CharField(choices=[('overview', 'Overview'), ('site', 'App / Site'), ('trafficSource', 'Traffic Source'), ('deviceCategory', 'Device Category'), ('country', 'Country'), ('carrier', 'Carrier / ISP'), ('browser', 'Browser')], db_index=True, help_text='Type of dimension breakdown', max_length=32)),
                ('dimension_value', models.CharField(blank=True, help_text="Specific value for the dimension (e.g., 'United States' for country)", max_length=255, null=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date of the report data')),
                ('currency', models.CharField(default='USD', help_text='Currency code for the revenue data', max_length=3)),
                ('impressions', models.BigIntegerField(default=0, help_text='Total impressions')),
                ('revenue', models.DecimalField(decimal_places=8, default=0, help_text='Total revenue in specified currency', max_digits=20)),
                ('ecpm', models.DecimalField(decimal_places=4, default=0, help_text='Effective cost per mille', max_digits=10)),
                ('clicks', models.BigIntegerField(default=0, help_text='Total clicks')),
                ('ctr', models.DecimalField(decimal_places=4, default=0, help_text='Click-through rate', max_digits=6)),
                ('fill_rate', models.DecimalField(decimal_places=4, default=0, help_text='Fill rate percentage', max_digits=6)),
                ('total_ad_requests', models.BigIntegerField(default=0, help_text='Total ad requests')),
                ('viewable_impressions_rate', models.DecimalField(decimal_places=4, default=0, help_text='Viewable impressions rate', max_digits=6)),
                ('unknown_revenue', models.DecimalField(decimal_places=8, default=0, help_text='Revenue from desktop devices marked as unknown', max_digits=20)),
                ('unknown_impressions', models.BigIntegerField(default=0, help_text='Impressions from desktop devices marked as unknown')),
                ('unknown_clicks', models.BigIntegerField(default=0, help_text='Clicks from desktop devices marked as unknown')),
                ('unknown_ecpm', models.DecimalField(decimal_places=2, default=0, help_text='eCPM from desktop devices marked as unknown', max_digits=20)),
                ('unknown_ctr', models.DecimalField(decimal_places=2, default=0, help_text='CTR from desktop devices marked as unknown', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(help_text='MCM invitation linking parent to child', on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.mcminvitation')),
                ('parent_network', models.ForeignKey(help_text='Parent GAM network that fetched this data', on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.gamnetwork')),
            ],
            options={
                'db_table': 'sub_report_data',
                'ordering': ['-date', 'dimension_type'],
                'indexes': [models.Index(fields=['date'], name='sub_report__date_33b336_idx'), models.Index(fields=['dimension_type', 'dimension_value'], name='sub_report__dimensi_1d582e_idx'), models.Index(fields=['parent_network'], name='sub_report__parent__601b8c_idx'), models.Index(fields=['child_network_code'], name='sub_report__child_n_f8173b_idx'), models.Index(fields=['invitation'], name='sub_report__invitat_950f55_idx'), models.Index(fields=['partner_id'], name='sub_report__partner_febaf1_idx'), models.Index(fields=['date', 'dimension_type', 'partner_id'], name='sub_report__date_fcbb2d_idx'), models.Index(fields=['parent_network', 'date'], name='sub_report__parent__8b4048_idx'), models.Index(fields=['child_network_code', 'date'], name='sub_report__child_n_6325ce_idx'), models.Index(fields=['date', 'unknown_revenue'], name='sub_report__date_57838a_idx'), models.Index(fields=['child_network_code', 'unknown_revenue'], name='sub_report__child_n_3ce63b_idx')],
                'unique_together': {('invitation', 'date', 'dimension_type', 'dimension_value')},
            },
        ),
    ]
