# Generated by Django 4.2.16 on 2025-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_subreportdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreportdata',
            name='viewable_impressions_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Viewable impressions rate', max_digits=8),
        ),
    ]
