# Generated by Django 4.2.16 on 2025-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_subreportdata_viewable_impressions_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreportdata',
            name='ctr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Click-through rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subreportdata',
            name='fill_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fill rate percentage', max_digits=8),
        ),
    ]
