# Generated by Django 4.2.16 on 2025-09-09 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0011_alter_mcminvitation_user_status'),
        ('reports', '0014_alter_subreportdata_ctr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subreportdata',
            options={'ordering': ['-date_to', 'dimension_type']},
        ),
        migrations.RemoveIndex(
            model_name='subreportdata',
            name='sub_report__date_33b336_idx',
        ),
        migrations.RemoveIndex(
            model_name='subreportdata',
            name='sub_report__date_fcbb2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='subreportdata',
            name='sub_report__parent__8b4048_idx',
        ),
        migrations.RemoveIndex(
            model_name='subreportdata',
            name='sub_report__child_n_6325ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='subreportdata',
            name='sub_report__date_57838a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='subreportdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subreportdata',
            name='date_from',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Start date of the aggregated period'),
        ),
        migrations.AddField(
            model_name='subreportdata',
            name='date_to',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='End date of the aggregated period'),
        ),
        migrations.AddField(
            model_name='subreportdata',
            name='timeframe',
            field=models.CharField(choices=[('month_to_date', 'Month to Date'), ('last_month', 'Last Month'), ('last_3_months', 'Last 3 Months'), ('last_6_months', 'Last 6 Months')], db_index=True, default='month_to_date', help_text='Timeframe for the aggregated data', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subreportdata',
            unique_together={('invitation', 'timeframe', 'dimension_type', 'dimension_value')},
        ),
        migrations.AddIndex(
            model_name='subreportdata',
            index=models.Index(fields=['timeframe'], name='sub_report__timefra_48f07c_idx'),
        ),
        migrations.AddIndex(
            model_name='subreportdata',
            index=models.Index(fields=['timeframe', 'dimension_type', 'partner_id'], name='sub_report__timefra_0313a1_idx'),
        ),
        migrations.AddIndex(
            model_name='subreportdata',
            index=models.Index(fields=['parent_network', 'timeframe'], name='sub_report__parent__b5c05d_idx'),
        ),
        migrations.AddIndex(
            model_name='subreportdata',
            index=models.Index(fields=['child_network_code', 'timeframe'], name='sub_report__child_n_ebde13_idx'),
        ),
        migrations.AddIndex(
            model_name='subreportdata',
            index=models.Index(fields=['date_from', 'date_to'], name='sub_report__date_fr_298dcf_idx'),
        ),
        migrations.RemoveField(
            model_name='subreportdata',
            name='date',
        ),
    ]
