# Generated by Django 4.2.16 on 2025-09-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_subreportdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermetadata',
            name='dimension_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('site', 'App / Site'), ('trafficSource', 'Traffic Source'), ('deviceCategory', 'Device Category'), ('country', 'Country'), ('carrier', 'Carrier / ISP'), ('browser', 'Browser'), ('country_carrier', 'Country + Carrier')], db_index=True, help_text='Type of dimension breakdown', max_length=32),
        ),
        migrations.DeleteModel(
            name='SubReportData',
        ),
    ]
