# Generated by Django 4.2.7 on 2025-09-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_mastermetadata_dimension_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastermetadata',
            options={'ordering': ['-date', 'child_network_code', 'dimension_type']},
        ),
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_partner_3a2297_idx',
        ),
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_date_85f966_idx',
        ),
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_parent__485d94_idx',
        ),
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_date_5b307e_idx',
        ),
        migrations.RemoveIndex(
            model_name='mastermetadata',
            name='master_meta_child_n_ce82f8_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_child_n_9516fb_idx',
            old_name='master_meta_child_n_b01a9a_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_dimensi_367222_idx',
            old_name='master_meta_dimensi_c7f92f_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_date_977a40_idx',
            old_name='master_meta_date_65d447_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_parent__228e39_idx',
            old_name='master_meta_parent__2d8b57_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_invitat_319bdb_idx',
            old_name='master_meta_invitat_92b549_idx',
        ),
        migrations.RenameIndex(
            model_name='mastermetadata',
            new_name='master_meta_child_n_227b8d_idx',
            old_name='master_meta_child_n_09f4cd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mastermetadata',
            unique_together={('child_network_code', 'dimension_type', 'dimension_value', 'date')},
        ),
        migrations.AddIndex(
            model_name='mastermetadata',
            index=models.Index(fields=['dimension_type', 'date'], name='master_meta_dimensi_e986ac_idx'),
        ),
        migrations.AlterModelTable(
            name='mastermetadata',
            table='master_metadata',
        ),
    ]
