# Generated by Django 4.2.7 on 2025-06-07 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GAMNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_code', models.CharField(max_length=20, unique=True)),
                ('network_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('network_type', models.CharField(choices=[('parent', 'Parent Network'), ('child', 'Child Network')], max_length=10)),
                ('currency_code', models.CharField(max_length=3)),
                ('time_zone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending MCM Invitation'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('service_account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_account_added', models.BooleanField(default=False)),
                ('api_version', models.CharField(default='v202508', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('parent_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_networks', to='gam_accounts.gamnetwork')),
            ],
            options={
                'verbose_name': 'GAM Network',
                'verbose_name_plural': 'GAM Networks',
                'ordering': ['network_name'],
            },
        ),
        migrations.CreateModel(
            name='UserNetworkPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('send_mcm_invitation', 'Send MCM Invitation'), ('verify_account', 'Verify Account Ownership'), ('access_reports', 'Access Reports'), ('manage_alerts', 'Manage Smart Alerts'), ('manage_websites', 'Manage Websites')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.gamnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'network', 'permission_type'],
                'unique_together': {('user', 'network', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='MCMInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_network_code', models.CharField(max_length=20)),
                ('child_network_name', models.CharField(blank=True, max_length=255)),
                ('invitation_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='gam_accounts.gamnetwork')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('parent_network', 'child_network_code')},
            },
        ),
    ]
