# Generated by Django 4.2.7 on 2025-06-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gam_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamnetwork',
            options={'verbose_name': 'GAM Network', 'verbose_name_plural': 'GAM Networks'},
        ),
        migrations.AlterModelOptions(
            name='mcminvitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'MCM Invitation', 'verbose_name_plural': 'MCM Invitations'},
        ),
        migrations.AlterModelOptions(
            name='usernetworkpermission',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Network Permission', 'verbose_name_plural': 'User Network Permissions'},
        ),
        migrations.AddField(
            model_name='mcminvitation',
            name='api_method_used',
            field=models.CharField(blank=True, help_text='Which API method succeeded (primary, alternative, manual)', max_length=50),
        ),
        migrations.AddField(
            model_name='mcminvitation',
            name='delegation_type',
            field=models.CharField(choices=[('MANAGE_INVENTORY', 'Manage Inventory'), ('MANAGE_ACCOUNT', 'Manage Account')], default='MANAGE_INVENTORY', help_text='Type of MCM delegation requested', max_length=20),
        ),
        migrations.AddField(
            model_name='mcminvitation',
            name='gam_company_id',
            field=models.CharField(blank=True, help_text='GAM Company ID returned from createCompanies API', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mcminvitation',
            name='primary_contact_email',
            field=models.EmailField(blank=True, help_text='Email address where invitation will be sent', max_length=254),
        ),
        migrations.AddField(
            model_name='mcminvitation',
            name='real_invitation_sent',
            field=models.BooleanField(default=False, help_text='True if sent via GAM API, False if manual workflow'),
        ),
        migrations.AddField(
            model_name='mcminvitation',
            name='revenue_share_percentage',
            field=models.IntegerField(blank=True, help_text='Percentage parent keeps (0-100), required for MANAGE_ACCOUNT', null=True),
        ),
        migrations.AddField(
            model_name='usernetworkpermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gamnetwork',
            name='api_version',
            field=models.CharField(default='v202505', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamnetwork',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='gamnetwork',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gamnetwork',
            name='service_account_email',
            field=models.EmailField(blank=True, default='report@hnt-gaming.iam.gserviceaccount.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamnetwork',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamnetwork',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='mcminvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcminvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mcminvitation',
            name='parent_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.gamnetwork'),
        ),
        migrations.AlterField(
            model_name='mcminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('awaiting_manual_send', 'Awaiting Manual Send'), ('api_error', 'API Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernetworkpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usernetworkpermission',
            name='network',
            field=models.ForeignKey(help_text='GAM network the permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='gam_accounts.gamnetwork'),
        ),
        migrations.AlterField(
            model_name='usernetworkpermission',
            name='permission_type',
            field=models.CharField(choices=[('send_mcm_invitation', 'Send MCM Invitation'), ('verify_account', 'Verify Account Ownership'), ('access_reports', 'Access Reports'), ('manage_alerts', 'Manage Smart Alerts'), ('manage_websites', 'Manage Websites'), ('full_access', 'Full Access')], help_text='Type of permission granted to user for this network', max_length=30),
        ),
        migrations.AlterField(
            model_name='usernetworkpermission',
            name='user',
            field=models.ForeignKey(help_text='Partner user who gets the permission', on_delete=django.db.models.deletion.CASCADE, related_name='network_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MCMInvitationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('api_attempt', 'API Attempt'), ('api_success', 'API Success'), ('api_failed', 'API Failed'), ('manual_sent', 'Manually Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gam_accounts.mcminvitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
