# Generated by Django 4.2.7 on 2025-07-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0004_assignedpartnerchildaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedPartnerAccount',
        ),
    ]
