# Generated by Django 4.2.7 on 2025-07-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0005_delete_assignedpartneraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcminvitation',
            name='comments',
            field=models.TextField(blank=True, help_text='Internal notes or comments', null=True),
        ),
        migrations.AddField(
            model_name='mcminvitation',
            name='invite_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('own', 'Own')], default='invitation', help_text='Type of invite: invitation or own', max_length=20),
        ),
        migrations.AddField(
            model_name='mcminvitation',
            name='site',
            field=models.URLField(blank=True, help_text='Primary site link (optional)', null=True),
        ),
    ]
