# Generated by Django 4.2.7 on 2025-07-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0006_mcminvitation_comments_mcminvitation_invite_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcminvitation',
            name='site',
            field=models.CharField(blank=True, help_text='Primary site link (optional)', max_length=255, null=True),
        ),
    ]
