# Generated by Django 4.2.7 on 2025-07-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0007_alter_mcminvitation_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedpartnerchildaccount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assignedpartnerchildaccount',
            name='invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gam_accounts.mcminvitation'),
        ),
    ]
