# Generated by Django 4.2.7 on 2025-07-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0008_alter_assignedpartnerchildaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcminvitation',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Admin-defined status (active/inactive)', max_length=20),
        ),
    ]
