# Generated by Django 4.2.7 on 2025-08-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0009_mcminvitation_user_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernetworkpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usernetworkpermission',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='usernetworkpermission',
            name='network',
        ),
        migrations.RemoveField(
            model_name='usernetworkpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='MCMInvitationLog',
        ),
        migrations.DeleteModel(
            name='UserNetworkPermission',
        ),
    ]
