# Generated by Django 4.2.7 on 2025-09-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0010_alter_usernetworkpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcminvitation',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='Admin-defined status (active/inactive)', max_length=20),
        ),
    ]
