# Generated by Django 4.2.7 on 2025-09-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0011_alter_mcminvitation_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('awaiting_manual_send', 'Awaiting Manual Send'), ('api_error', 'API Error'), ('invited', 'Invited'), ('approved', 'Approved'), ('reject_by_child', 'Reject By Child'), ('withdrawn_by_parent', 'Withdrawn by Parent'), ('closed_policy_violation', 'Closed Policy Violation'), ('closed_invalid_activity', 'Closed Invalid Activity')], default='pending', max_length=30),
        ),
    ]
