# Generated by Django 4.2.7 on 2025-09-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0012_add_extended_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamnetwork',
            name='service_account_enabled',
            field=models.BooleanField(default=False, help_text='Whether the service account/key is enabled for API access'),
        ),
        migrations.AlterField(
            model_name='mcminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('awaiting_manual_send', 'Awaiting Manual Send'), ('api_error', 'API Error'), ('reject_by_child', 'Reject By Child'), ('withdrawn_by_parent', 'Withdrawn by Parent'), ('closed_policy_violation', 'Closed Policy Violation'), ('closed_invalid_activity', 'Closed Invalid Activity')], default='pending', max_length=30),
        ),
    ]
