# Generated by Django 4.2.7 on 2025-09-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0014_alter_mcminvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcminvitation',
            name='service_account_enabled',
            field=models.BooleanField(default=False, help_text='Whether the service account/key is enabled for API access for this child network'),
        ),
    ]
