# Generated by Django 4.2.7 on 2025-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0015_mcminvitation_service_account_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcminvitation',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Admin-defined status (active/inactive)', max_length=20),
        ),
    ]
