# Generated by Django 4.2.7 on 2025-10-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gam_accounts', '0016_alter_mcminvitation_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamnetwork',
            name='api_version',
            field=models.CharField(default='v202508', max_length=20),
        ),
    ]
